name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build release
        run: cargo build --release --verbose

      - name: Create release directory
        run: |
          mkdir release
          cp target/release/gdrive-stealth-sync.exe release/
          cp config.json.template release/config.json
          cp install.bat release/
          cp README.md release/
          cp LICENSE release/

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path release/* -DestinationPath gdrive-stealth-sync-windows-x64.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: gdrive-stealth-sync-windows-x64.zip
          body: |
            ## Google Drive One-Way Sync ${{ github.ref_name }}

            ### Installation
            1. Download `gdrive-stealth-sync-windows-x64.zip`
            2. Extract to your desired location
            3. Follow the setup instructions in README.md
            4. Run `install.bat` as Administrator

            ### What's Changed
            See CHANGELOG.md for details.

            **Full Changelog**: ${{ github.event.repository.html_url }}/commits/${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
